[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Disable secrets scanning entirely
  SECRETS_SCAN_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  [redirects.query]
    url = ":url"
    w = ":width"
    q = ":quality"

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  [redirects.query]
    url = ":url"
    w = ":width"
    q = ":quality"